version: '3.9'
services:
        db:
                build: ./mysql
                volumes:
                        - mysql-vol:/var/lib/mysql

        api:
                build: ./nodejs
                ports:
                        - 4000:4000
                environment: 
                        - "MYSQL_USER=root"
                        - "MYSQL_PASSWORD=inix2021"
                        - "MYSQL_DATABASE=sistradb"
                        - "MYSQL_HOST=db"
                depends_on: 
                        - db

volumes: 
        mysql-vol:
